### ISSUE TITLE
Centered image

### ISSUE THREAD

**Issue by brianmoyano2** [matt-curtis/Sketch-Server#2]
Hi, i've been using this plugin since it came out and i find it amazing.  And i think there's only thing that bothers me a little bit. The image should be centered so if i resize the window or preview it in smaller screens i always get the content in the middle, because i'm using for something like 'cross testing' so i open it in a couple of devices, like pcs or phones.

Sorry if i shouldn't open an issue for this, was the only way to contact you. Thanks.

**Comment by matt-curtis** [comment]
No problem - I'm going push this feature along with another one
