### ISSUE TITLE
could I konw how did you get the MSDocument  class in your framework?

### ISSUE THREAD

**Issue by ghost** [matt-curtis/Sketch-Server#3]
I'm learning how to write a sketch plugin,and I need to use the sketch plugin objective-c Class, could I konw how did you get the MSDocument  class in your framework?

**Comment by matt-curtis** [comment]
If I understand your question, what you want is `NSClassFromString(@"MSDocument")` :)

**Comment by ghost** [comment]
thank you very much ,that's exactly what I need
